"""Write every refusal an agent or a person can be shown, as one list to read through.

    python tools/audit/refusals.py            # rewrite docs/api/refusal-messages.txt
    python tools/audit/refusals.py --check    # exit 1 if the file is not what this writes

audit-agent-surface 1.3. A refusal is reviewed where it is written, one at a time, and
nobody reads them as a set: that is how one came to advise a spec's author to edit a class
attribute. This reads the source and lists each message as its author wrote it, with the
values it fills in shown in braces, under the function that raises it.

It lists what reaches the two surfaces: every `raise` with a message outside
`anvilate.analysis`, and every line the command line prints to standard error. The
closed-form functions under `analysis/` refuse their own arguments in one pattern, are
swept by their own tests, and are counted here, not listed. A message built somewhere the
`raise` cannot see (a variable, a helper's return) is listed as `<built elsewhere>`.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "src" / "anvilate"
PAGE = REPO / "docs" / "api" / "refusal-messages.txt"


def _text(node: ast.expr) -> str | None:
    """A message as written: literals as they are, each interpolated value in braces."""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.JoinedStr):
        return "".join(
            part.value if isinstance(part, ast.Constant) else "{" + ast.unparse(part.value) + "}"
            for part in node.values
        )
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        left, right = _text(node.left), _text(node.right)
        if left is None and right is None:
            return None
        return (left or "{...}") + (right or "{...}")
    if isinstance(node, ast.IfExp):
        first, second = _text(node.body), _text(node.orelse)
        if first is not None and second is not None:
            return f"{first} | {second}"
    return None


def _owner(tree: ast.Module) -> dict[int, str]:
    """The innermost function each line belongs to, by line number."""
    owner: dict[int, str] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            for line in range(node.lineno, (node.end_lineno or node.lineno) + 1):
                owner[line] = node.name  # a nested function is walked later and wins
    return owner


def _to_stderr(call: ast.Call) -> bool:
    return (
        isinstance(call.func, ast.Name)
        and call.func.id == "print"
        and any(
            keyword.arg == "file" and ast.unparse(keyword.value) in ("err", "sys.stderr")
            for keyword in call.keywords
        )
    )


def refusals() -> tuple[dict[str, list[tuple[str, str]]], int]:
    """Each listed module's ``(function, message)`` pairs in source order, and how many
    raise sites ``analysis/`` holds."""
    listed: dict[str, list[tuple[str, str]]] = {}
    analysis = 0
    for path in sorted(SOURCE.rglob("*.py")):
        module = path.relative_to(SOURCE).as_posix()
        tree = ast.parse(path.read_text(encoding="utf-8"))
        owner = _owner(tree)
        found: list[tuple[int, str, str]] = []
        for node in ast.walk(tree):
            message: ast.expr | None = None
            if isinstance(node, ast.Raise) and isinstance(node.exc, ast.Call) and node.exc.args:
                if module.startswith("analysis/"):
                    analysis += 1
                    continue
                message = node.exc.args[0]
            elif isinstance(node, ast.Call) and _to_stderr(node) and node.args:
                message = node.args[0]
            if message is not None:
                text = _text(message) or "<built elsewhere>"
                found.append(
                    (node.lineno, owner.get(node.lineno, "<module>"), " ".join(text.split()))
                )
        if found:
            listed[module] = [(function, text) for _line, function, text in sorted(found)]
    return listed, analysis


def page() -> str:
    listed, analysis = refusals()
    total = sum(len(rows) for rows in listed.values())
    lines = [
        "# Every refusal the command line or the MCP server can show, as written.",
        "# Generated by tools/audit/refusals.py; do not edit. One per line, under its module,",
        "# as `function: message`, with each value the message fills in shown in braces.",
        f"# {total} messages in {len(listed)} modules. The {analysis} raise sites under",
        "# analysis/ refuse a function's own arguments and are not listed here.",
    ]
    for module, rows in listed.items():
        lines += ["", f"[{module}]"]
        lines += [f"{function}: {text}" for function, text in rows]
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if "--check" in argv:
        if not PAGE.is_file() or PAGE.read_text(encoding="utf-8") != page():
            print(f"{PAGE.relative_to(REPO)} is stale; run tools/audit/refusals.py")
            return 1
        return 0
    PAGE.write_text(page(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
