"""Write the drawable-parts catalog page and one picture per pattern.

    python tools/parts-catalog/build.py            # rewrite docs/parts-catalog.md and docs/parts/
    python tools/parts-catalog/build.py --check    # exit 1 if the page is not what this writes

The page is generated from the pattern registry (`anvilate.patterns.drawable_catalog`) and
each picture is the overview render of that pattern's worked example, so a pattern cannot
ship without appearing here. `tests/test_parts_catalog.py` holds the page to this script.
"""

# ruff: noqa: E501 - the page's table rows are long lines of Markdown
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
PAGE = REPO / "docs" / "parts-catalog.md"
PICTURES = REPO / "docs" / "parts"

_HEAD = """# Parts you can ask for

Every part on this page is one `element_type` in a Design Spec. Ask your agent for it in
plain words ("a 120 by 80 mounting plate, 6 mm thick, with four M6 clearance holes") and it
writes the spec, calls `build_part`, and shows you the picture. `export_artifact` then
writes a STEP file to open in your own CAD.

A part marked **drawn, not checked** has no strength or fit screen: its picture and its
STEP file are geometry, not a verdict, and its exports carry the unvalidated mark. A part
marked **envelope** is a catalog component drawn from its tabulated size: where it goes,
not how it is made.

A shape that is not on this page belongs in your CAD. Start from the STEP export of the
closest part here.

This page is generated by `tools/parts-catalog/build.py` from the pattern registry.
"""

_FEATURES = """## Holes and slots

Parts that take holes declare them the same way, positioned from the centre of the face
they are cut into. A hole that does not fit, or that overlaps another, is refused by name
before anything is built.

| Declaration | Fields |
| --- | --- |
| `Hole` | `tag`, `x`, `y`, `diameter`, and `kind`: `through`, `counterbore` (with `counterbore_diameter`, `counterbore_depth`) or `countersink` (with `head_diameter`). `thread` marks it tapped, as data. |
| `HolePattern` | `tag`, `diameter`, and `kind`: `rectangular` (`count_x`, `count_y`, `pitch_x`, `pitch_y`) or `bolt_circle` (`count`, `circle_diameter`, `start_angle_deg`). |
| `Slot` | `tag`, `x`, `y`, `length`, `width`, `angle_deg`. |

Each cut is measurable by its tag: `measure_geometry` answers `feature:<tag>:diameter`,
`feature:<tag>:x` and `feature_count`.
"""


def page() -> str:
    """The catalog page, as text."""
    from anvilate.patterns import drawable_catalog

    sections = [_HEAD, _FEATURES, "## The parts\n"]
    for entry in drawable_catalog():
        marks = []
        if not entry["screened"]:
            marks.append("**drawn, not checked**")
        if entry["envelope"]:
            marks.append("**envelope**")
        required = [p for p in entry["parameters"] if p["required"]]
        optional = [p for p in entry["parameters"] if not p["required"]]

        def listed(parameters: list[dict]) -> str:
            return ", ".join(f"`{p['name']}` ({p['takes']})" for p in parameters) or "none"

        sections.append(
            "\n".join(
                [
                    f"### `{entry['element_type']}`",
                    "",
                    entry["summary"] + (" " + ", ".join(marks) + "." if marks else ""),
                    "",
                    f"![{entry['element_type']}](parts/{entry['element_type']}.png)",
                    "",
                    f"- Required: {listed(required)}",
                    f"- Optional: {listed(optional)}",
                    f"- Outputs: {', '.join(entry['outputs'])}",
                    f"- Example: [`examples/{entry['example']}`](../examples/{entry['example']})",
                    "",
                ]
            )
        )
    return "\n".join(sections)


def pictures() -> dict[str, bytes]:
    """The overview PNG of every pattern's worked example, by element type."""
    from anvilate import projection
    from anvilate.geometry import build_spec
    from anvilate.patterns import patterns
    from anvilate.raster import svg_to_png
    from anvilate.spec import load_spec_yaml

    drawn = {}
    for element_type, pattern in sorted(patterns().items()):
        spec = load_spec_yaml((REPO / "examples" / pattern.example).read_text(encoding="utf-8"))
        built = build_spec(spec)
        # The stroke font has no comma or slash, so the line is written without them.
        line = "has a screen" if pattern.screened else "drawn - not checked"
        lines = [("envelope - " if pattern.envelope else "") + line]
        svg, _height = projection.render_overview(
            built.shape, built.faces, name=built.name, lines=lines, width_px=720, unit="mm"
        )
        drawn[element_type] = svg_to_png(svg)
    return drawn


def main(argv: list[str]) -> int:
    if "--check" in argv:
        if PAGE.read_text(encoding="utf-8") != page():
            print(f"{PAGE.relative_to(REPO)} is stale; run tools/parts-catalog/build.py")
            return 1
        return 0
    PAGE.write_text(page(), encoding="utf-8")
    PICTURES.mkdir(exist_ok=True)
    for element_type, png in pictures().items():
        (PICTURES / f"{element_type}.png").write_bytes(png)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
