"""Anvilate T1 analytical checks: closed-form, deterministic, no solver.

The T1 validation tier screens a design with handbook closed-form solutions
(Roark, Shigley) before any FEA — fast, deterministic, and unit-checked. The
modules:

- :mod:`~anvilate.analysis.axial` — direct axial stress, section area, and the
  minimum area an axial load requires
- :mod:`~anvilate.analysis.beam` — bending (cantilever / simply-supported /
  fixed-fixed / fixed-pinned; point, distributed, triangular, patch, and
  applied-couple loads), transverse shear, section second moments
- :mod:`~anvilate.analysis.plate` — flat-plate bending (simply-supported
  rectangle via the exact Navier series; circular, simply-supported and clamped),
  and the clamped-cover thickness a pressure requires
- :mod:`~anvilate.analysis.section` — ``CrossSection`` bundling area, second
  moment, extreme fibre, section modulus, and radius of gyration; the bending
  stress a moment makes and the minimum section modulus it requires
- :mod:`~anvilate.analysis.column` — Euler and Johnson buckling, slenderness,
  and the minimum section second moment a load requires
- :mod:`~anvilate.analysis.torsion` — the torque a power/speed makes, solid and
  hollow shaft torsion, twist, torsional stiffness, and the shaft diameter a
  torque requires; thin-walled rectangular (box) tube torsion (Bredt) and thin
  open-section (strip) torsion
- :mod:`~anvilate.analysis.pressure_vessel` — thin-wall cylinder and sphere,
  exact Lamé thick-wall cylinder and sphere, and the wall thickness a pressure
  requires
- :mod:`~anvilate.analysis.interference` — thick-wall press/shrink-fit (Lamé)
- :mod:`~anvilate.analysis.contact` — Hertzian point (sphere) and line (cylinder) contact
- :mod:`~anvilate.analysis.fastener` — bolt torque-tension, bearing, shear, and
  the ISO 898 tensile stress area / axial stress
- :mod:`~anvilate.analysis.keys` — shaft-key shear and bearing stress, and the
  key length a torque requires
- :mod:`~anvilate.analysis.weld` — fillet-weld throat shear and the weld leg a
  load requires
- :mod:`~anvilate.analysis.spring` — helical-spring shear (Wahl), rate, and
  lateral (column) buckling screen
- :mod:`~anvilate.analysis.thermal` — thermal growth, constrained thermal
  stress, shrink-fit assembly temperature, and CTE-mismatch (differential)
  joint stress
- :mod:`~anvilate.analysis.dynamics` — modal screens: SDOF and Rayleigh
  estimates, the Dunkerley multi-mass combination, distributed-mass beam
  fundamentals, disc-on-shaft torsional mode
- :mod:`~anvilate.analysis.stress` — von Mises combination, combined axial+bending
- :mod:`~anvilate.analysis.fatigue` — Goodman, Soderberg, and Gerber fatigue,
  the max/min → amplitude/mean cyclic-stress converter, the fatigue notch factor,
  and the steel endurance-limit estimate

Further analytical cases land here as they are built out (see
openspec/specs/validation-gauntlet/).
"""

from __future__ import annotations

from .axial import axial_stress, circular_area, required_axial_area
from .beam import (
    SHEAR_FORM_CIRCULAR,
    SHEAR_FORM_RECTANGULAR,
    BeamBendingResult,
    cantilever_center_patch_load,
    cantilever_end_load,
    cantilever_end_moment,
    cantilever_offset_load,
    cantilever_offset_moment,
    cantilever_partial_uniform_load,
    cantilever_triangular_load,
    cantilever_triangular_load_peak_at_tip,
    cantilever_uniform_load,
    circular_second_moment,
    deflection_scorecard,
    fixed_fixed_center_load,
    fixed_fixed_center_patch_load,
    fixed_fixed_offset_load,
    fixed_fixed_partial_uniform_load,
    fixed_fixed_triangular_load,
    fixed_fixed_uniform_load,
    fixed_pinned_center_load,
    fixed_pinned_center_patch_load,
    fixed_pinned_end_moment,
    fixed_pinned_offset_load,
    fixed_pinned_partial_uniform_load,
    fixed_pinned_triangular_load,
    fixed_pinned_triangular_load_peak_at_prop,
    fixed_pinned_uniform_load,
    hollow_circular_second_moment,
    max_transverse_shear_stress,
    overhang_tip_load,
    overhang_uniform_load,
    rectangular_second_moment,
    simply_supported_center_load,
    simply_supported_center_patch_load,
    simply_supported_end_moment,
    simply_supported_offset_load,
    simply_supported_offset_moment,
    simply_supported_partial_uniform_load,
    simply_supported_symmetric_point_loads,
    simply_supported_triangular_load,
    simply_supported_uniform_load,
    span_deflection_limit,
)
from .column import (
    ColumnEnd,
    euler_buckling_load,
    euler_critical_stress,
    euler_second_moment_for_load,
    johnson_critical_stress,
    radius_of_gyration,
    secant_column_max_stress,
    slenderness_ratio,
    transition_slenderness,
)
from .contact import (
    HertzContact,
    HertzLineContact,
    hertz_cylinder_contact,
    hertz_effective_modulus,
    hertz_sphere_contact,
)
from .dynamics import (
    STANDARD_GRAVITY,
    cantilever_fundamental_frequency,
    clamped_annular_plate_fundamental_frequency,
    clamped_circular_plate_fundamental_frequency,
    clamped_plate_fundamental_frequency,
    dunkerley_fundamental_frequency,
    fixed_fixed_fundamental_frequency,
    fixed_pinned_fundamental_frequency,
    frequency_scorecard,
    natural_frequency,
    natural_frequency_from_deflection,
    simply_supported_annular_plate_fundamental_frequency,
    simply_supported_circular_plate_fundamental_frequency,
    simply_supported_fundamental_frequency,
    simply_supported_plate_fundamental_frequency,
    solid_disc_polar_mass_moment,
    spring_surge_frequency,
    torsional_natural_frequency,
)
from .fastener import (
    NUT_FACTOR_AS_RECEIVED,
    bearing_stress,
    bolt_axial_stress,
    bolt_diameter_for_shear,
    bolt_preload_from_torque,
    bolt_shear_stress,
    bolt_tensile_stress_area,
    thread_stripping_shear_area,
    thread_stripping_stress,
    torque_for_preload,
)
from .fatigue import (
    CyclicStress,
    cyclic_stress_components,
    estimated_endurance_limit,
    fatigue_notch_factor,
    gerber_safety_factor,
    gerber_scorecard,
    goodman_safety_factor,
    goodman_scorecard,
    soderberg_safety_factor,
    soderberg_scorecard,
)
from .interference import (
    InterferenceFit,
    interference_axial_capacity,
    interference_fit,
    interference_for_contact_pressure,
    interference_torque_capacity,
)
from .keys import (
    KeyLengthRequirement,
    key_bearing_stress,
    key_length_for_torque,
    key_shear_stress,
    key_tangential_force,
)
from .plate import (
    PlateBendingResult,
    clamped_annular_plate_uniform_load,
    clamped_circular_plate_thickness_for_pressure,
    clamped_circular_plate_uniform_load,
    clamped_plate_uniform_load,
    simply_supported_annular_plate_uniform_load,
    simply_supported_circular_plate_uniform_load,
    simply_supported_plate_center_patch_load,
    simply_supported_plate_uniform_load,
)
from .pressure_vessel import (
    ThickWallSphereStress,
    ThickWallStress,
    ThinWallStress,
    thick_wall_cylinder,
    thick_wall_sphere,
    thin_wall_cylinder,
    thin_wall_sphere_stress,
    thin_wall_thickness_for_pressure,
)
from .section import CrossSection, bending_stress, required_section_modulus
from .spring import (
    SPRING_END_CLAMPED_FREE,
    SPRING_END_FIXED_HINGED,
    SPRING_END_HINGED_HINGED,
    SPRING_END_PARALLEL_PLATES,
    SpringBucklingResult,
    helical_spring_buckling,
    helical_spring_rate,
    spring_index,
    spring_shear_stress,
    spring_stored_energy,
    wahl_factor,
)
from .stress import (
    CombinedNormalStress,
    combine_axial_bending,
    concentrated_stress,
    max_shear_stress_plane,
    principal_stresses_plane,
    strength_scorecard,
    tresca_equivalent_stress,
    tresca_principal,
    von_mises_bending_torsion,
    von_mises_plane_stress,
    von_mises_principal,
    yield_safety_factor,
)
from .thermal import (
    DifferentialThermalStress,
    constrained_thermal_stress,
    differential_thermal_stress,
    free_thermal_expansion,
    shrink_fit_assembly_temperature,
)
from .torsion import (
    hollow_shaft_torsional_stress,
    hollow_shaft_twist_angle,
    polar_second_moment_hollow,
    polar_second_moment_solid,
    rectangular_tube_enclosed_area,
    rectangular_tube_torsional_stress,
    rectangular_tube_twist_angle,
    shaft_diameter_for_torque,
    shaft_torsional_stiffness,
    shaft_torsional_stress,
    shaft_twist_angle,
    thin_open_strip_torsion_constant,
    thin_open_strip_torsional_stress,
    thin_open_strip_twist_angle,
    torque_from_power,
)
from .weld import (
    FILLET_THROAT_FACTOR,
    fillet_weld_leg_for_load,
    fillet_weld_throat_stress,
)

__all__ = [
    "axial_stress",
    "circular_area",
    "required_axial_area",
    "BeamBendingResult",
    "cantilever_center_patch_load",
    "cantilever_end_load",
    "cantilever_end_moment",
    "cantilever_offset_load",
    "cantilever_offset_moment",
    "cantilever_partial_uniform_load",
    "cantilever_triangular_load",
    "cantilever_triangular_load_peak_at_tip",
    "cantilever_uniform_load",
    "simply_supported_center_load",
    "simply_supported_center_patch_load",
    "simply_supported_end_moment",
    "simply_supported_offset_load",
    "simply_supported_offset_moment",
    "simply_supported_partial_uniform_load",
    "simply_supported_symmetric_point_loads",
    "simply_supported_triangular_load",
    "simply_supported_uniform_load",
    "fixed_fixed_center_load",
    "fixed_fixed_center_patch_load",
    "fixed_fixed_offset_load",
    "fixed_fixed_partial_uniform_load",
    "fixed_fixed_triangular_load",
    "fixed_fixed_uniform_load",
    "fixed_pinned_center_load",
    "fixed_pinned_center_patch_load",
    "fixed_pinned_end_moment",
    "fixed_pinned_offset_load",
    "fixed_pinned_partial_uniform_load",
    "fixed_pinned_triangular_load",
    "fixed_pinned_triangular_load_peak_at_prop",
    "fixed_pinned_uniform_load",
    "overhang_tip_load",
    "overhang_uniform_load",
    "rectangular_second_moment",
    "circular_second_moment",
    "hollow_circular_second_moment",
    "CrossSection",
    "bending_stress",
    "required_section_modulus",
    "max_transverse_shear_stress",
    "deflection_scorecard",
    "span_deflection_limit",
    "SHEAR_FORM_RECTANGULAR",
    "SHEAR_FORM_CIRCULAR",
    "ColumnEnd",
    "euler_buckling_load",
    "euler_second_moment_for_load",
    "radius_of_gyration",
    "slenderness_ratio",
    "euler_critical_stress",
    "transition_slenderness",
    "johnson_critical_stress",
    "secant_column_max_stress",
    "STANDARD_GRAVITY",
    "natural_frequency",
    "natural_frequency_from_deflection",
    "dunkerley_fundamental_frequency",
    "cantilever_fundamental_frequency",
    "simply_supported_fundamental_frequency",
    "fixed_fixed_fundamental_frequency",
    "fixed_pinned_fundamental_frequency",
    "simply_supported_plate_fundamental_frequency",
    "clamped_plate_fundamental_frequency",
    "simply_supported_circular_plate_fundamental_frequency",
    "clamped_circular_plate_fundamental_frequency",
    "simply_supported_annular_plate_fundamental_frequency",
    "clamped_annular_plate_fundamental_frequency",
    "torsional_natural_frequency",
    "solid_disc_polar_mass_moment",
    "frequency_scorecard",
    "NUT_FACTOR_AS_RECEIVED",
    "bolt_preload_from_torque",
    "torque_for_preload",
    "bearing_stress",
    "bolt_shear_stress",
    "bolt_diameter_for_shear",
    "bolt_tensile_stress_area",
    "bolt_axial_stress",
    "thread_stripping_shear_area",
    "thread_stripping_stress",
    "goodman_safety_factor",
    "goodman_scorecard",
    "soderberg_safety_factor",
    "soderberg_scorecard",
    "gerber_safety_factor",
    "gerber_scorecard",
    "CyclicStress",
    "cyclic_stress_components",
    "estimated_endurance_limit",
    "fatigue_notch_factor",
    "key_tangential_force",
    "key_shear_stress",
    "key_bearing_stress",
    "KeyLengthRequirement",
    "key_length_for_torque",
    "polar_second_moment_solid",
    "polar_second_moment_hollow",
    "shaft_torsional_stress",
    "shaft_diameter_for_torque",
    "hollow_shaft_torsional_stress",
    "torque_from_power",
    "shaft_twist_angle",
    "hollow_shaft_twist_angle",
    "shaft_torsional_stiffness",
    "rectangular_tube_enclosed_area",
    "rectangular_tube_torsional_stress",
    "rectangular_tube_twist_angle",
    "thin_open_strip_torsion_constant",
    "thin_open_strip_torsional_stress",
    "thin_open_strip_twist_angle",
    "PlateBendingResult",
    "simply_supported_plate_uniform_load",
    "simply_supported_plate_center_patch_load",
    "clamped_plate_uniform_load",
    "simply_supported_circular_plate_uniform_load",
    "clamped_circular_plate_uniform_load",
    "simply_supported_annular_plate_uniform_load",
    "clamped_annular_plate_uniform_load",
    "clamped_circular_plate_thickness_for_pressure",
    "ThinWallStress",
    "ThickWallStress",
    "ThickWallSphereStress",
    "thin_wall_cylinder",
    "thin_wall_thickness_for_pressure",
    "thick_wall_cylinder",
    "thin_wall_sphere_stress",
    "thick_wall_sphere",
    "InterferenceFit",
    "interference_fit",
    "interference_for_contact_pressure",
    "interference_axial_capacity",
    "interference_torque_capacity",
    "hertz_effective_modulus",
    "HertzContact",
    "hertz_sphere_contact",
    "HertzLineContact",
    "hertz_cylinder_contact",
    "spring_index",
    "wahl_factor",
    "spring_shear_stress",
    "helical_spring_rate",
    "SPRING_END_PARALLEL_PLATES",
    "SPRING_END_FIXED_HINGED",
    "SPRING_END_HINGED_HINGED",
    "SPRING_END_CLAMPED_FREE",
    "SpringBucklingResult",
    "helical_spring_buckling",
    "spring_stored_energy",
    "spring_surge_frequency",
    "von_mises_plane_stress",
    "von_mises_bending_torsion",
    "von_mises_principal",
    "principal_stresses_plane",
    "max_shear_stress_plane",
    "tresca_equivalent_stress",
    "tresca_principal",
    "yield_safety_factor",
    "strength_scorecard",
    "CombinedNormalStress",
    "combine_axial_bending",
    "concentrated_stress",
    "constrained_thermal_stress",
    "free_thermal_expansion",
    "shrink_fit_assembly_temperature",
    "DifferentialThermalStress",
    "differential_thermal_stress",
    "FILLET_THROAT_FACTOR",
    "fillet_weld_throat_stress",
    "fillet_weld_leg_for_load",
]
