"""T1 analytical piezoelectric-transducer checks (closed-form).

A piezoelectric material converts mechanical stress into electric charge and back, with no moving
parts. Pressing on it produces a charge (the direct effect — the physics of a force sensor,
accelerometer, or energy harvester); applying a voltage strains it (the converse effect — a
precision actuator or ultrasonic driver). This is a distinct electromechanical transduction from the
resistive strain gauge of :mod:`anvilate.analysis.strain_gauge`: the gauge needs an excitation
supply and reads strain as a resistance change, while a piezo makes its own charge directly.

The direct effect gives the charge from the applied force through the charge coefficient d33,
Q = d33 * F — the current a harvester or sensor delivers. Left open-circuit, the same stress builds
a voltage through the voltage coefficient g33 = d33 / epsilon, V = g33 * sigma * t, from the stress
and the electrode gap (thickness) t; this is the volt-level signal an unloaded sensor produces and
can reach tens of volts for a modest push. Reading the direct effect the other way, F = Q / d33 gets
the force behind a measured charge — how a piezo load washer or force sensor is read out.

Sources: IEEE 176 (standard on piezoelectricity) — the charge q = d33·F a force generates along
the poling axis, the open-circuit voltage it develops across the element's capacitance, and the
force a measured charge infers.
"""

from __future__ import annotations

from ..units import Quantity

__all__ = [
    "piezoelectric_charge",
    "piezoelectric_force_from_charge",
    "piezoelectric_open_circuit_voltage",
]


def piezoelectric_charge(*, charge_coefficient: Quantity, force: Quantity) -> Quantity:
    """The charge generated by an applied force, Q = d33 * F.

    The direct piezoelectric effect: the electric charge a ``force`` F produces through the
    ``charge_coefficient`` d33 (about 300-600 pC/N for PZT), Q = d33 * F. It is the charge a force
    sensor delivers or an impact harvester scavenges, proportional to the force with no threshold.
    Returns the charge in coulomb.
    """
    _check(charge_coefficient, "[current]*[time]/[force]", "charge_coefficient")
    _check(force, "[force]", "force")
    d33 = charge_coefficient.to("C/N").magnitude
    f = force.to("N").magnitude
    return Quantity(magnitude=d33 * f, unit="C")


def piezoelectric_open_circuit_voltage(
    *, voltage_coefficient: Quantity, stress: Quantity, thickness: Quantity
) -> Quantity:
    """The open-circuit voltage from an applied stress, V = g33 * sigma * t.

    The voltage an unloaded (open-circuit) element develops under a ``stress`` sigma across an
    electrode gap ``thickness`` t, through the ``voltage_coefficient`` g33 (= d33 / permittivity),
    V = g33 * sigma * t. It is the signal a piezo sensor puts out with no electrical load, and can
    reach tens of volts for a modest stress on a millimetre-scale element. Returns the voltage in V.
    """
    _check(voltage_coefficient, "[electric_potential]*[length]/[force]", "voltage_coefficient")
    _check(stress, "[pressure]", "stress")
    _check(thickness, "[length]", "thickness")
    g33 = voltage_coefficient.to("V*m/N").magnitude
    sigma = stress.to("Pa").magnitude
    t = thickness.to("m").magnitude
    if t <= 0:
        raise ValueError("thickness must be positive")
    return Quantity(magnitude=g33 * sigma * t, unit="V")


def piezoelectric_force_from_charge(*, charge: Quantity, charge_coefficient: Quantity) -> Quantity:
    """The force behind a measured charge, F = Q / d33.

    The sensor inverse of :func:`piezoelectric_charge`: the ``force`` a piezo load washer or force
    sensor felt, recovered from the measured ``charge`` Q and the ``charge_coefficient`` d33,
    F = Q / d33. It is how a charge amplifier's reading becomes a force. Returns the force in N.
    """
    _check(charge, "[current]*[time]", "charge")
    _check(charge_coefficient, "[current]*[time]/[force]", "charge_coefficient")
    q = charge.to("C").magnitude
    d33 = charge_coefficient.to("C/N").magnitude
    if d33 <= 0:
        raise ValueError("charge_coefficient must be positive")
    return Quantity(magnitude=q / d33, unit="N")


def _check(value: Quantity, expected: str, name: str) -> None:
    if not value.has_dimension(expected):
        raise ValueError(
            f"{name} must be a {expected} quantity; got {value.dimensionality} ({value})"
        )
